version: '3.7'
services:
  number:
    image: service1numbers:build-${BUILD_NUMBER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
    container_name: service10numbers
    build: ./number
  letter:
    image: service2letters:build-${BUILD_NUMBER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
    container_name: service20letters
    build: ./letter
  backend:
    image: service3gen:build-${BUILD_NUMBER}
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
    container_name: service30gen
    build: ./backend
    environment:
    - DATABASE_URI=mysql+pymysql://root:mypassword@mysqldb/proj2db 
    - SECRET_KEY=secretkey

  mysqldb:
    image: mysqldb:latest   
    ports:
    - target: 3306
      published: 3306
    volumes:
    - flasksql:/var/lib/mysql   
    environment: 
    - MYSQL_ROOT_PASSWORD=mypassword

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - target: 80
        published: 80
    depends_on:
      - service4front
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

volumes:
  flasksql:
