version: '3.7'
services:
  service1numbers: 
    image: service1numbers:latest
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy: 
     replicas: 4
   
  service2letters:
    image: service2letters:latest
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
     replicas: 4
    
  service3gen:
    image: service3gen:latest
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
     replicas: 4

  service4front:
    image: service4front:latest
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
    deploy:
     replicas: 4
    environment:
    - SECRET_KEY=secretkey

  mysqldb:
    image: mysqldb:latest   
    ports:
    - target: 3306
      published: 3306
    volumes:
    - flasksql:/var/lib/mysql   
    environment: 
    - MYSQL_ROOT_PASSWORD=mypassword

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - target: 80
        published: 80
    depends_on:
      - service4front
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

volumes:
  flasksql:


