version: '3.7'
services:
  service1numbers: 
    image: service1numbers:latest
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy: 
     replicas: 4
   
 service2letters:
    image: service2letters:latest
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
     replicas: 4
    
  service3gen:
    image: service3gen:latest
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
     replicas: 4
    environment:
    - SECRET_KEY=hello
    
  frontend:
    image: zreginaldoz/frontend:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
     replicas: 4
    
