version: '3.7'
services:
  service1numbers: 
    image: service1numbers:latest
    ports:
      - "5002:5002"
      protocol: tcp
    deploy: 
     replicas: 4
   
  service2letters:
    image: service2letters:latest
    ports:
      - "5001:5001"
      protocol: tcp
    deploy:
     replicas: 4
    
  service3gen:
    image: service3gen:latest
    ports:
      - "5003:5003"
      protocol: tcp
    deploy:
     replicas: 4

  service4front:
    image: service4front:latest
    ports:
      - "5004:5004"
      protocol:tcp
    deploy:
     replicas: 4

  #servicedb:
   # images:
   # ports:
   #   - "3306:3306"

